### PR TITLE
[FEATURE] Subresource Integrity (SRI) generation for v:asset.script …

### PR DESCRIPTION
**Pull request by 4-lom**
…and style

Vhs can now automaticly generate and add the SRI to the resulting asset tag.
This can be turned on through the option 'assets.tagsAddIntegrityAttribute'.
These values are possible: 0 = off | 1 = sha256 | 2 = sha384 | 3 = sha512

Example: plugin.tx_vhs.assets.tagsAddIntegrityAttribute = 2

This will result in something like...

Example: `<script type="..." src="js/your.js" integrity="sha384-6XaWTzGb6esk97...">`

Resolves: #1094

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Exactly what we needed ;) thanks!

**Comment by cedricziel** [comment]
Great! Thanks a bunch!

+1 from my side

**Comment by NamelessCoder** [comment]
Manually picked - thanks Ruben :)

**Comment by typo3ua** [comment]
This is feature only work when attribute standalone="0" and SRI Hash is generated automatically
How to be if I want to add in the integrity attribute the own value which I get from https://srihash.org/?

**Pull request closed without merging**
