### PR TITLE
[TASK] Depend on typo3/cms-core rather than typo3/cms for v9 compat 

### PR DESCRIPTION
**Pull request by cedricziel**
Let's see how that goes..

### CODE REVIEW

**Comment by NamelessCoder** [comment]
@cedricziel I think this dep is also set in `fluidtypo3/development`, but perhaps we can safely remove it from there / set that to `typo3/cms-core` as well.

**Comment by cedricziel** [comment]
Re-visiting this, one problem is that CMS-Core is only available 7.6 and up. So should we burn the bridge just yet?

**Comment by cedricziel** [comment]
*8.7 and up, corrected it above. Extra comment for e-mailers.

**Comment by bmack** [comment]
@cedricziel can you rebase?

**Comment by cedricziel** [comment]
@bmack updated the branch

**Comment by NamelessCoder** [comment]
Implemented in https://github.com/FluidTYPO3/vhs/pull/1457

**Pull request closed without merging**
