### PR TITLE
[TASK] Require TYPO3Fluid/Fluid compiling Traits

### PR DESCRIPTION
**Pull request by NamelessCoder**
Traits are now available on TYPO3 7.6.13+ and this
version is set as minimum required TYPO3 version.

See https://review.typo3.org/#/c/50676/

### CODE REVIEW

**Comment by NamelessCoder** [comment]
FYI: CompilableInterface is deprecated but required by LTS to detect compiling support. It may be possible to remove after 7.6.14 or 7.6.15 but doesn't hurt if it stays.

**Comment by cedricziel** [comment]
Saw you fiddeling in the development repo. You might want to check https://semver.mwl.be/#?package=typo3%2Fcms&version=%3E%3D7.6.13,%20%3C%3D7.6.99%7C%5E8.4.1&minimum-stability=stable next time :)

**Comment by NamelessCoder** [comment]
Hehe thanks, that would have saved some trouble.

**Comment by cedricziel** [comment]
Rebase pls

**Comment by cedricziel** [comment]
Looks like a bunch of changes are necessary. I'll check back tomorrow :)

**Comment by NamelessCoder** [comment]
It might not be too bad - but see you tomorrow ;) thanks for merging!

**Comment by NamelessCoder** [comment]
There we go! After this one, other PRs need some attention. And then conversion of the rest of the ViewHelpers. And then... done.

**Comment by cedricziel** [comment]
Yeah. Back to green. - Thx a bunch!

**Pull request merged**
