### PR TITLE
[TASK] Transform into full documentation

### PR DESCRIPTION
**Pull request by alexander-nitsche**
In the [first step](https://github.com/FluidTYPO3/vhs/pull/1762) the README.md was aligned to the documentation standards and published at docs.typo3.org. In this second step the documentation is transformed into a full documentation, making use of all advantages of the TYPO3 Sphinx theme and being searchable by the global search on docs.typo3.org.

What remains: Rendering the view helper documentation automatically into the Documentation/ViewHelpers/ folder.

### CODE REVIEW

**Comment by alexander-nitsche** [comment]
How it looks:
Screen Shot 2022-05-08 at 12 21 13

**Comment by NamelessCoder** [comment]
Thanks for your work @alexander-nitsche!

Is there a way to avoid converting the changelog MD files? These are both automatically generated and have permalinks in various places (which are outside our control). I would even be OK with the changelog item just being a link to the GitHub listing of the MD files.

**Comment by alexander-nitsche** [comment]
No problem. The TYPO3 Sphinx theme support Markdown in a reduced way, which is almost fine for the changelogs (only problem are the links to the diff view of the patch). It is still important to have the changelog integrated into the full documentation so that i added a note about rendering flaws and that the user could navigate to the GitHub view in doubt (amended in commit "[[DOCS] Integrate changelog into full documentation](https://github.com/FluidTYPO3/vhs/pull/1769/commits/6dd284ee3ed07408d4c55e06f48bb781cfcc045c)").

**Comment by NamelessCoder** [comment]
Still a minor problem - the changelog index is also automatically generated as MD - and it looks like the files in Documentation/Classes were dropped without conversion?

**Review by NamelessCoder — APPROVED** [review]

**Pull request merged**
