### PR TITLE
[TASK] Use FQN for global function calls to improve performance

### LINKED ISSUE #1528: Optimizing PHP performance by using fullyqualified function calls
Overall performance could be improved by using FQN for global function calls. So PHP doesn't need to lookup the global functions in the namespace context. More information to this topic can be found here:
https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

Change could be easily done withe php-cs-fixer rule `native_function_invocation`..

### PR DESCRIPTION
**Pull request by carstendietrich**
Use FQN names to improve performance for function lookups.
See: https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

I used latest php-cs-fixer to do the changes:
`php-cs-fixer fix vhs --rules=native_function_invocation --allow-risky=yes`

Closes #1528

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Hi Carsten - thanks for taking time to prepare a (well-formed!) pull request. However, I'm afraid I have to reject this change and refer to my input for the TYPO3 core when this change was proposed there. The same objections still stand and would also be applicable to a solution that imports the functions with `use`. Apologies for straight-out rejecting but this will not be done.

https://decisions.typo3.org/t/should-we-use-fully-qualified-function-fqn-calls-like-is-array-in-the-core/392/5

For posterity and TL;DR: the benefit is absolutely marginal, whatever performance it *does* affect should be solved in PHP itself, it takes an inordinate amount of time to explain why it has to be done - and we cannot expect new contributors to adopt and always use such a rule without explaining it first.

**Comment by NamelessCoder** [comment]
Hi Carsten - thanks for taking time to prepare a (well-formed!) pull request. However, I'm afraid I have to reject this change and refer to my input for the TYPO3 core when this change was proposed there. The same objections still stand and would also be applicable to a solution that imports the functions with `use`. Apologies for straight-out rejecting but this will not be done.

https://decisions.typo3.org/t/should-we-use-fully-qualified-function-fqn-calls-like-is-array-in-the-core/392/5

For posterity and TL;DR: the benefit is absolutely marginal, whatever performance it *does* affect should be solved in PHP itself, it takes an inordinate amount of time to explain why it has to be done - and we cannot expect new contributors to adopt and always use such a rule without explaining it first.

**Comment by NamelessCoder** [comment]
Hi Carsten - thanks for taking time to prepare a (well-formed!) pull request. However, I'm afraid I have to reject this change and refer to my input for the TYPO3 core when this change was proposed there. The same objections still stand and would also be applicable to a solution that imports the functions with `use`. Apologies for straight-out rejecting but this will not be done.

https://decisions.typo3.org/t/should-we-use-fully-qualified-function-fqn-calls-like-is-array-in-the-core/392/5

For posterity and TL;DR: the benefit is absolutely marginal, whatever performance it *does* affect should be solved in PHP itself, it takes an inordinate amount of time to explain why it has to be done - and we cannot expect new contributors to adopt and always use such a rule without explaining it first.

**Comment by NamelessCoder** [comment]
Hi Carsten - thanks for taking time to prepare a (well-formed!) pull request. However, I'm afraid I have to reject this change and refer to my input for the TYPO3 core when this change was proposed there. The same objections still stand and would also be applicable to a solution that imports the functions with `use`. Apologies for straight-out rejecting but this will not be done.

https://decisions.typo3.org/t/should-we-use-fully-qualified-function-fqn-calls-like-is-array-in-the-core/392/5

For posterity and TL;DR: the benefit is absolutely marginal, whatever performance it *does* affect should be solved in PHP itself, it takes an inordinate amount of time to explain why it has to be done - and we cannot expect new contributors to adopt and always use such a rule without explaining it first.

**Comment by NamelessCoder** [comment]
Hi Carsten - thanks for taking time to prepare a (well-formed!) pull request. However, I'm afraid I have to reject this change and refer to my input for the TYPO3 core when this change was proposed there. The same objections still stand and would also be applicable to a solution that imports the functions with `use`. Apologies for straight-out rejecting but this will not be done.

https://decisions.typo3.org/t/should-we-use-fully-qualified-function-fqn-calls-like-is-array-in-the-core/392/5

For posterity and TL;DR: the benefit is absolutely marginal, whatever performance it *does* affect should be solved in PHP itself, it takes an inordinate amount of time to explain why it has to be done - and we cannot expect new contributors to adopt and always use such a rule without explaining it first.

**Comment by NamelessCoder** [comment]
Hi Carsten - thanks for taking time to prepare a (well-formed!) pull request. However, I'm afraid I have to reject this change and refer to my input for the TYPO3 core when this change was proposed there. The same objections still stand and would also be applicable to a solution that imports the functions with `use`. Apologies for straight-out rejecting but this will not be done.

https://decisions.typo3.org/t/should-we-use-fully-qualified-function-fqn-calls-like-is-array-in-the-core/392/5

For posterity and TL;DR: the benefit is absolutely marginal, whatever performance it *does* affect should be solved in PHP itself, it takes an inordinate amount of time to explain why it has to be done - and we cannot expect new contributors to adopt and always use such a rule without explaining it first.

**Comment by NamelessCoder** [comment]
Hi Carsten - thanks for taking time to prepare a (well-formed!) pull request. However, I'm afraid I have to reject this change and refer to my input for the TYPO3 core when this change was proposed there. The same objections still stand and would also be applicable to a solution that imports the functions with `use`. Apologies for straight-out rejecting but this will not be done.

https://decisions.typo3.org/t/should-we-use-fully-qualified-function-fqn-calls-like-is-array-in-the-core/392/5

For posterity and TL;DR: the benefit is absolutely marginal, whatever performance it *does* affect should be solved in PHP itself, it takes an inordinate amount of time to explain why it has to be done - and we cannot expect new contributors to adopt and always use such a rule without explaining it first.

**Comment by NamelessCoder** [comment]
Sorry about the spam there. Although from here it looked like it didn't, GitHub actually received all the comments...

**Comment by carstendietrich** [comment]
Hey Claus,

thanks for the fast response. I can totally understand your point. I guess we have to wait till PHP solves this. At least there is already a RFC under discussion:
https://wiki.php.net/rfc/fallback-to-root-scope-deprecation

**Comment by NamelessCoder** [comment]
Thanks for the RFC link Carsten, and for understanding the reasons! I *knew* this was something PHP would get to sooner or later ;)

**Pull request closed without merging**
