### PR TITLE
[TASK] Make VHS a bit more TYPO3/CMS independent

### PR DESCRIPTION
**Pull request by jmverges**
Refactor TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper to TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper

### CODE REVIEW

**Comment by cedricziel** [comment]
I don't think it's a good idea to solve it that way. Especially replacing imports on viewhelpers with *hard* dependencies on the CMS.

**Comment by jmverges** [comment]
Do we have something like a list of those that don't have hard dependencies?

**Comment by cedricziel** [comment]
You can create such list pretty easily: Just grep for `Utility::`` and ignore occurences of the 3 utilities we have in the project. That should find roughly 97.75% of them.

**Comment by jmverges** [comment]
Classes/Asset.php
Classes/Service/AssetService.php
Classes/Service/PageService.php
Classes/Traits/ArrayConsumingViewHelperTrait.php
Classes/Traits/PageRendererTrait.php
Classes/Traits/SlideViewHelperTrait.php
Classes/Traits/SourceSetViewHelperTrait.php
Classes/Utility/CoreUtility.php
Classes/Utility/FrontendSimulationUtility.php
Classes/View/UncacheTemplateView.php
Classes/ViewHelpers/Asset/AbstractAssetViewHelper.php
Classes/ViewHelpers/Asset/PrefetchViewHelper.php
Classes/ViewHelpers/Condition/Context/IsDevelopmentViewHelper.php
Classes/ViewHelpers/Condition/Context/IsProductionViewHelper.php
Classes/ViewHelpers/Condition/Context/IsTestingViewHelper.php
Classes/ViewHelpers/Condition/Form/HasValidatorViewHelper.php
Classes/ViewHelpers/Condition/Page/HasSubpagesViewHelper.php
Classes/ViewHelpers/Context/GetViewHelper.php
Classes/ViewHelpers/DebugViewHelper.php
Classes/ViewHelpers/Extension/AbstractExtensionViewHelper.php
Classes/ViewHelpers/Extension/IconViewHelper.php
Classes/ViewHelpers/Extension/LoadedViewHelper.php
Classes/ViewHelpers/Extension/Path/AbsoluteViewHelper.php
Classes/ViewHelpers/Extension/Path/RelativeViewHelper.php
Classes/ViewHelpers/Extension/Path/ResourcesViewHelper.php
Classes/ViewHelpers/Extension/Path/SiteRelativeViewHelper.php
Classes/ViewHelpers/Format/CaseViewHelper.php
Classes/ViewHelpers/Format/MarkdownViewHelper.php
Classes/ViewHelpers/Format/Placeholder/LipsumViewHelper.php
Classes/ViewHelpers/Format/RemoveXssViewHelper.php
Classes/ViewHelpers/Iterator/ExtractViewHelper.php
Classes/ViewHelpers/Iterator/SortViewHelper.php
Classes/ViewHelpers/LViewHelper.php
Classes/ViewHelpers/Media/AbstractMediaViewHelper.php
Classes/ViewHelpers/Media/AudioViewHelper.php
Classes/ViewHelpers/Media/ExistsViewHelper.php
Classes/ViewHelpers/Media/ExtensionViewHelper.php
Classes/ViewHelpers/Media/FilesViewHelper.php
Classes/ViewHelpers/Media/Image/AbstractImageInfoViewHelper.php
Classes/ViewHelpers/Media/Image/AbstractImageViewHelper.php
Classes/ViewHelpers/Media/PdfThumbnailViewHelper.php
Classes/ViewHelpers/Media/SizeViewHelper.php
Classes/ViewHelpers/Media/SourceViewHelper.php
Classes/ViewHelpers/Media/VideoViewHelper.php
Classes/ViewHelpers/Menu/AbstractMenuViewHelper.php
Classes/ViewHelpers/OrViewHelper.php
Classes/ViewHelpers/Page/AbsoluteUrlViewHelper.php
Classes/ViewHelpers/Page/Header/AlternateViewHelper.php
Classes/ViewHelpers/Page/InfoViewHelper.php
Classes/ViewHelpers/Page/LanguageMenuViewHelper.php
Classes/ViewHelpers/Page/LanguageViewHelper.php
Classes/ViewHelpers/Page/LinkViewHelper.php
Classes/ViewHelpers/Page/Resources/FalViewHelper.php
Classes/ViewHelpers/Render/CacheViewHelper.php
Classes/ViewHelpers/Render/TemplateViewHelper.php
Classes/ViewHelpers/Render/UncacheViewHelper.php
Classes/ViewHelpers/Resource/AbstractImageViewHelper.php
Classes/ViewHelpers/Resource/AbstractResourceViewHelper.php
Classes/ViewHelpers/Resource/LanguageViewHelper.php
Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php
Classes/ViewHelpers/Resource/Record/FalViewHelper.php
Classes/ViewHelpers/Site/UrlViewHelper.php
Classes/ViewHelpers/Uri/RequestViewHelper.php
Classes/ViewHelpers/Variable/ConvertViewHelper.php
Classes/ViewHelpers/Variable/ExtensionConfigurationViewHelper.php
Classes/ViewHelpers/Variable/TyposcriptViewHelper.php

66 from 90, could make sense for the 24 without Utility?

**Comment by NamelessCoder** [comment]
We will do this some day - but not until we drop 7.6 LTS support and VHS is separated into general-purpose non-TYPO3 ViewHelpers and the original VHS package includes those as a dependency.

**Pull request closed without merging**
