### PR TITLE
Support constants in v:format.replace

### PR DESCRIPTION
**Pull request by neufeind**
Resolves: #1413

### CODE REVIEW

**Comment by neufeind** [comment]
Solution follows the code from "Iterator / ExplodeViewHelper". But if we want to support constants in more places maybe we should extract that tool-functionality to a central place?

**Comment by NamelessCoder** [comment]
> But if we want to support constants in more places maybe we should extract that tool-functionality to a central place?

This sounds appropriate, if nothing else then to avoid code duplication. It would be fine to put this in a Utility that we then call on the argument value before using it as glue/delimiter/substring/whatever.

FYI, in the case of this particular ViewHelper and probably some others, I would require that this resolving becomes opt-in via a new argument, for example `resolveConstants`, so this addition does not change any current behavior. The reason being that in the implode and explode ViewHelpers it is trivial to allow this as you almost always split or glue with a single character - but in the replace and other ViewHelpers there's much greater chance someone intentionally searched for `constant:LF` and did not expect that this gets resolved to `\n` before replacement happens.

**Comment by NamelessCoder** [comment]
We might also consider suggesting https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/ConstViewHelper.php as a valid alternative way to get this support in *every* ViewHelper. Using this in a ViewHelper argument would allow that exact resolving of any constant, e.g. `subject="{v:const(name: 'PHP_EOL')}"`.

**Comment by NamelessCoder** [comment]
Won't add/fix - please use `v:const` for all your constant extraction needs ;)

**Pull request closed without merging**
