### PR TITLE
[BUGFIX] fixed #865 ImageViewHelper are now respect fully qualified uri

### LINKED ISSUE #865: v:resource.image does not respect fully qualified uri's
I use http://typo3.org/extensions/repository/view/aus_driver_local_cdn as File Storege Driver.
So the image uri is http://cdn.mydomain.tld/my-image.jpg but the `ImageViewHelper` encodes the uri so my image.source is `http%3A//cdn.mydomain.tld/my-image.jpg` . The problem is in the `preprocessImages` and the `preprocessSourceUri`-method in the `FluidTYPO3\Vhs\ViewHelpers\Resource\AbstractImageViewHelper`, there is no check for a fully qualified uri

    $imageSource = $GLOBALS['TSFE']->absRefPrefix . GeneralUtility::rawUrlEncodeFP($imageInfo[3]);

to

    if(GeneralUtility::isValidUrl($imageInfo[3])) {
        $imageSource = $imageInfo[3];
    } else {
        $imageSource = $GLOBALS['TSFE']->absRefPrefix . GeneralUtility::rawUrlEncodeFP($imageInfo[3]);
    }

### PR DESCRIPTION
**Pull request by mischka**

### CODE REVIEW

**Comment by xf-** [comment]
Please follow the CGL and add a commit message with Prefix and Comment - not only a ticket reference.

**Comment by mischka** [comment]
@xf- I hope this comment is ok

**Comment by xf-** [comment]
THX for the update.
fixed #865 is not needed. You can put that in comment in github :)

Last thing CGL
compare like this in your condition.
https://github.com/FluidTYPO3/vhs/pull/866/files#diff-acfe6735e0cd552917b9be6e7f286938L117

**Comment by mischka** [comment]
@xf- now the condition and the codestyle looks correct to me

**Comment by cedricziel** [comment]
I rebased and squashed your changes.

Once merged, this ticket will destroy itself automatically, Mr Hunt.

**Pull request closed without merging**
