### PR TITLE
[BUGFIX] Don't urlencode image urls

### PR DESCRIPTION
**Pull request by bjo3rnf**
Addresses #1364. To be honest I don't remember why url encoding was used in the first place here so chances are this breaks something else. Testing and feedback is highly appreciated.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Looks like this was added as part of a much larger change back in 2015:

https://github.com/bjo3rnf/vhs/commit/4db4ed567f74e3fef25c452fe5d6d337dc79c615#diff-dd3c40c66dd2d2443cb3e8be9e0cf6d6R48

If anything is broken by this patch I would presume it would be related to responsive images.

**Comment by NamelessCoder** [comment]
Approved but don't merge until verified.

**Comment by NamelessCoder** [comment]
FYI, the TYPO3 core change log explicitly says to use raw url encoding as substitute for that removed/deprecated method so if the problem is that those just behave differently (removed method didn't escape this exact byte) then I'd like to know so I can adapt the TYPO3 core change log message and explain the difference ;)

**Comment by bjo3rnf** [comment]
> the TYPO3 core change log explicitly says to use raw url encoding as substitute for that removed/deprecated method

Ok, but I can't think of a good reason to encode a file's url in the first place.

**Comment by bjo3rnf** [comment]
To quote myself:

> Ok, but I can't think of a good reason to encode a file's url in the first place.

I think I found one. The problem here was that the full path to the image was urlencoded which includes all slashes. There might be rare cases where the filename contains an already escaped slash which should be encoded of course. Should we consider this edge case as valid or leave as is @NamelessCoder?

**Comment by NamelessCoder** [comment]
@bjo3rnf You answered the question with a pull request - best way to answer! :)

**Pull request merged**
