### PR TITLE
[TASK] Remove v:switch and v:case

### PR DESCRIPTION
**Pull request by NamelessCoder**
Can be safely migrated by string-replacing `v:switch` to `f:switch` and `v:case` to `f:case`.

### CODE REVIEW

**Comment by cedricziel** [comment]
That woul mean vhs 3.0 - is there anything we can release upfront?

**Comment by NamelessCoder** [comment]
That is exactly what that would mean :)

We can make a bugfix release for 2.4.1 if necessary.

**Comment by NamelessCoder** [comment]
We could also make class aliases. I'll do that!

**Comment by cedricziel** [comment]
Alright - great idea!

**Comment by cedricziel** [comment]
Are they 100% compatible argument-wise?

**Comment by NamelessCoder** [comment]
> Are they 100% compatible argument-wise?

Hmm, now that you mention it... they're not. We do have to remove these without aliases, and the migration description needs to include argument differences.

**Comment by cedricziel** [comment]
Agreed. :)

**Comment by TheNaderio** [comment]
Someone shold mark the v:switch as DEPRECATED in the viewhelper reference at:
https://fluidtypo3.org/viewhelpers/vhs/master/SwitchViewHelper.html

**Pull request merged**
