### PR TITLE
Fal misassignments

### PR DESCRIPTION
**Pull request by cedricziel**
Based on #1119 , so please merge the other one first.

### CODE REVIEW

**Comment by cedricziel** [comment]
Ahh. Damn. Rebasing killed your amendments, sorry ^^

**Comment by NamelessCoder** [comment]
No worries - it affected a previous commit so it shouldn't be in this PR anyway.

**Comment by NamelessCoder** [comment]
was the multiple space indentation in phpdoc arguments at https://github.com/FluidTYPO3/vhs/pull/1119/files#diff-2b0c07312881d3f18820898d71ff3d50R51 - will make a manual commit.

**Comment by cedricziel** [comment]
Ahh, that one - I thought i'd removed 'em.

Thx for the manual rework and the review!

**Pull request merged**
