### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by cedricziel**

### CODE REVIEW

**Comment by cedricziel** [comment]
Ahh. Forgot to rebase. Will do later.

**Comment by cedricziel** [comment]
just remade it. There's a lot of inconsistencies I tried to address.
Though we're dynamically typed, i think especially announced return types should match.

**Comment by NamelessCoder** [comment]
* Needs rebase
* The `Tx_Extbase_DomainObject_DomainObjectInterface` usage can be switched to the new class name
* When the class is global, just reference it using `\RuntimeException` and so on - no need to import those.
* And what @bjo3rnf said :)

**Comment by cedricziel** [comment]
Crap-a-chino. Once again merge conflicts. Stop working ^^

**Pull request merged**
