### PR TITLE
[BUGFIX] Slides now working. Missing call to getSlideRecords.

### PR DESCRIPTION
**Pull request by monosize**
Change getSlideRecordsFromPage. to only check if there are valid resources.
#1103

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Hey @monosize - could you give a quick explanation why it is necessary to duplicate the entire `render()` method? The functionality it provides, including the sliding, should already be provided by either base class or Trait.

**Comment by monosize** [comment]
@NamelessCoder - in the render method from Class ```FluidTYPO3\Vhs\ViewHelpers\Resource\Record\AbstractRecordResourceViewHelper```  is no call to ```getSlideRecords```. 
see in AbstractRecordResourceViewHelper https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Resource/Record/AbstractRecordResourceViewHelper.php#L197

and here in the PR https://github.com/FluidTYPO3/vhs/pull/1127/commits/0a42f58c7ca7e1b52ef4b9cb1d3108874aea6dfd#diff-3b954cee31eae4dcef6f278f8bde4461R79

**Comment by NamelessCoder** [comment]
The intention is that sliding should only be available if the VH also implements the `SlideViewHelperTrait` which is what defines the `getSlideRecordsFromPage` that you are actually addressing. It looks like incorrect use of the logic contains within that Trait.

I don't have the full picture but looks to me like the proper solution would be to implement `SlideViewHelperTrait` in the `FalViewHelper`, assuming that the problem you face isn't because you actually meant to use for example `v:page.resources.fal` which is a specific FAL "record resource" ViewHelper that enables sliding because `pages` contains sliding. This record resource ViewHelper is after all intended to be generic for any record type (not just those supporting parent->child relations!). If I am missing a use case here, please elaborate ;)

Maybe this solves your use case?

**Comment by NamelessCoder** [comment]
@monosize Did https://github.com/FluidTYPO3/vhs/pull/1186 also solve this issue? Seems they touch the same code at least.

**Comment by NamelessCoder** [comment]
Quite sure this is solved - during my testing over the past weeks I have been using sliding the whole time.

**Pull request closed without merging**
