### PR TITLE
Fixes page sliding in page.resources.fal ViewHelper

### LINKED ISSUE #1103: slide not working on FluidTYPO3\Vhs\ViewHelpers\Page\Resources\FalViewHelper
I try to display the first media element on page using slide -1. On the page the record is assigned to it works fine, put on any descendant page no resources are fetched.

``` html
<v:page.resources.fal table="pages" field="media" as="resources" slide="-1">
    <v:variable.set name="bgImage" value="{resources.0.url}"/>
</v:page.resources.fal>
<if condition="{bgImage}">
    <v:asset.style content=".image-bg { background-image: url('/{bgImage}'); }" />
</if>
```

It worked in vhs 2.4.0, but does not work in vhs 3.0.1

Edit: I am using TYPO3 CMS 7.6.10

### LINKED ISSUE #1173: After updating from 2.4 to 3.1 v.page.resources.fal delivers empty array
Hi,

after updating vhs from 2.4 to 3.1 I have a problem with the v:page.resources.fal viewhelper. In a lot of my projects the editors get the possibility to change the header of the pages uploading an image to page resources. In vhs 2.4.0 the header partial is filled with the image by (works fine):

`<v:page.resources.fal table="pages" field="media" uid="{page.uid}" as="images" slide="-1">
	<f:for each="{images}" as="image">
		<f:image src="{image.url}" alt="{image.alternative}" />
	</f:for>
</v:page.resources.fal>`

After updating to some version from vhs 3 I get an empty array for "images". I read the issue of the page.info viewhelper in case of reading something from a sysfolder. Maybe it has something to do with that, because in my case the masterpages in the trees where the editor should upload are a pagetype shortcut to the first subpage in the tree. If I use a standard page from the tree the viewhelper is working. Changing every shortcut masterpage to defaut pages would be really bad for me. Is there any possibilty to change that back to the former behavior?

Best regards in my bumpy English :-)
Markus

### PR DESCRIPTION
**Pull request by cbrunet**
Fixes #1173 . Fixes #1103 .

getSlideRecords function was not called.

### CODE REVIEW

**Comment by cedricziel** [comment]
Thank you, @cbrunet , @dmitryd , @NamelessCoder .

I think the comment is sufficient and serves the purpose well.

**Comment by NamelessCoder** [comment]
Keep an open eye on those squash-merge commit topics! This one lacks a prefix.

**Comment by cedricziel** [comment]
Ach.

Yeah. Never understood why we wouldn't use merge commits. Do you want me to force-fix it?

**Comment by cedricziel** [comment]
...and you did it in the meantime... ^^

**Comment by NamelessCoder** [comment]
Already fixed it, no worries!

**Comment by educo-adymorz** [comment]
@cbrunet @dmitryd @NamelessCoder @cedricziel 

Thank you for fixing this issue.

**Comment by dmitryd** [comment]
Yes, looks good to me :)

**Pull request merged**
