### PR TITLE
[TASK] Proper rendering of mountpoints

### LINKED ISSUE #541: Mountpoints not working in v:page.menu
I've tried to use Mountpoints but when I create the menu with the v:page.menu ViewHelper (vhs, version 1.8.4) the Mountpoint is shown as redirect instead as Mountpoint. Is there a solution for it?

### PR DESCRIPTION
**Pull request by bjo3rnf**
Fixes #541 and inspired by @benjaminrau's 15e7b9fee6

### CODE REVIEW

**Comment by phifa** [comment]
This is still not working. Too bad. I guess I have to switch back to a TS menu. Any updates on this?

**Comment by NamelessCoder** [comment]
Please open a new issue if you experience problems - this one has been closed for more than two years now.

**Comment by cedricziel** [comment]
Locked.

**Comment by bjo3rnf** [comment]
I'm afraid this is a "won't fix". Even the menu viewhelpers included in FluidStyledContent are unable to handle mountpoints. TS is the way to go here most probably.

**Pull request merged**
