### PR TITLE
Fix Title attribute in PictureViewHelper.php

### PR DESCRIPTION
**Pull request by danielkuehni**
Title attribute was set to 'alt' argument.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Thanks Daniel!

**Comment by cedricziel** [comment]
Target branches can be changed on the fly :)

**Comment by NamelessCoder** [comment]
Tell me how, @cedricziel! That's a great feature!

**Comment by NamelessCoder** [comment]
Nevermind, found it. Aaaah how nice.

**Comment by cedricziel** [comment]
Yeah, it's pretty amazing-and around for quite a while now :)

**Comment by NamelessCoder** [comment]
GitHub just gets better and better :)

**Pull request merged**
