### PR TITLE
[TASK] Deprecate/remove unused code

### PR DESCRIPTION
**Pull request by bjo3rnf**
Addresses #1081

### CODE REVIEW

**Comment by NamelessCoder** [comment]
Hey buddy - would you mind firing off a rebase on this one? The build issues should be fixed now :)

**Comment by bjo3rnf** [comment]
Done. Lots of warnings in phpunit though.

**Comment by NamelessCoder** [comment]
Looks like a single CGL issue remains - no phpunit errors afaics? HHVM fails, sure, but that's allowed ;)

**Comment by cedricziel** [comment]
Seems fine. #teamMerge

**Comment by bjo3rnf** [comment]
Hm, I can't see the CGL issue. Line 690 is the very last line...?

**Comment by NamelessCoder** [comment]
Is it a ghost? It could be a ghost. I hope it's not a ghost!

**Pull request merged**
