### PR TITLE
Check for usergroup instead for user on page-rights

### PR DESCRIPTION
**Pull request by MoppieMop**
Some Extensions assign only usergroup and no user - so its better to check for usergroup.

P.S. Sorry, but I don't know how to exclude my previous commit in tidy-Viewhelper. I'am git-noob.

### CODE REVIEW

**Comment by MoppieMop** [comment]
Had to change the condition so "hide at login" works correctly.

**Comment by bjo3rnf** [comment]
Hi @MoppieMop,

this requires some additional touch indeed ^^ but we can sort that out better on IRC I guess. You'd have to create a new branch from the current development branch first and apply your changes there. Plus the commit message should start with [BUGFIX] and describe what is actually fixed.

Cheers
Björn

**Comment by MoppieMop** [comment]
Ok I'll try it. I have to create a new PR, right?

**Comment by bjo3rnf** [comment]
Not necessarily, no. You can rewind your development branch, rebase, apply your changes and force push. A new branch is not mandatory (although I mentioned it above).

**Pull request closed without merging**
