### PR TITLE
[BUGFIX] v:page.menu Render pages with access

### PR DESCRIPTION
**Pull request by 7elix**
In specific setup the TSFE->fe_user contains array config.
Ensures that pages are shown with access setup: "hide on login".

### CODE REVIEW

**Comment by 7elix** [comment]
#1062

**Comment by NamelessCoder** [comment]
Hi Felix,

I'm not sure this is an issue any longer? @bjo3rnf did a major refactoring of the menu ViewHelpers to scrap much of our custom methods to get menu etc. - I've gone through the code as it is now on the development branch, and it doesn't seem like we're selecting pages this way anymore? Maybe @bjo3rnf can elaborate!

In any case, the PageSelectService class no longer exists on the development branch so if we need this patch, we'll need it put in another place (which again I'm hoping @bjo3rnf can point out to save me some time). On a general level I recommend always creating a new branch based on development, then publishing that to your fork and creating the PR from there - makes it easier to add more commits or amend the existing one without messing with your clean state on your local development branch ;)

**Comment by bjo3rnf** [comment]
> it doesn't seem like we're selecting pages this way anymore

That's correct. Current development branch should work as expected.

**Comment by NamelessCoder** [comment]
I'll take the liberty of closing this one - if there still is an issue on the `development` branch we of course need to fix that, but this patch will not apply on that branch any longer.

**Comment by 7elix** [comment]
Not a problem with develop

**Pull request closed without merging**
