### PR TITLE
[FEATURE] Added v:if, deprecating v:if.condition / v:if.condition.extend

### PR DESCRIPTION
**Pull request by danilobuerger**
Examples:

``` xml
<v:if stack="{0: {0: 'foo'}, 1: '==', 2: {0: 'foo'}}">
    <f:then>IF THEN (YES)</f:then>
    <f:else>IF ELSE</f:else>
</v:if>
```

``` xml
<v:if stack="{0: {0: 'foo'}, 1: '==', 2: 3}">
    <f:then>IF THEN</f:then>
    <f:else>IF ELSE (YES)</f:else>
</v:if>
```

``` xml
<v:if stack="{0: 1, 1: '==', 2: 1, 3: 'AND', 4: 1}">
    <f:then>IF THEN (YES)</f:then>
    <f:else>IF ELSE</f:else>
</v:if>
```

``` xml
<v:if stack="{0: 1, 1: '==', 2: 1, 3: 'AND', 4: {0: 1, 1: '!=', 2: 0}}">
    <f:then>IF THEN (YES)</f:then>
    <f:else>IF ELSE</f:else>
</v:if>
```

``` xml
<v:if stack="{0: {0: 'foo', 1: '!=', 2: 'bar'}, 1: 'AND', 2: 1, 3: 'OR', 4: {0: 1, 1: '==', 2: 0}}">
    <f:then>IF THEN (YES)</f:then>
    <f:else>IF ELSE</f:else>
</v:if>
```

### CODE REVIEW

**Comment by dextar1** [comment]
how these conditions will be written if i needed {Error1} =! NULL || {Error2} =! NULL || {Error3} =! NULL

**Comment by NamelessCoder** [comment]
`{v:if(stack: {0: Error1, 1: '||', 2: Error2, 3: '||', 4: Error3})}` (off the top of head). See also https://fluidtypo3.org/viewhelpers/vhs/master/IfViewHelper.html

**Comment by dextar1** [comment]
Curly Brackets are not needed? i am sending data from Controller like {NameError}

**Comment by NamelessCoder** [comment]
No curly braces needed. If Fluid sees a plain string without quotes used as argument, it assumes you mean an ObjectAccessorNode to access that variable.

**Comment by dextar1** [comment]
thats great. thank you very much :-)

**Pull request merged**
