### PR TITLE
Update LinkViewHelper.php

### PR DESCRIPTION
**Pull request by beam2web**
Problem:
====
The commit removes empty class attributes for anchors and removes whitespaces around the classes. The class should be only rendered if there are no empty strings or whitespaces inside.

Test:
====

```
No class attribute should be appear
<v:page.link
    pageUid="13"
    title="link without class attribute" />
<v:page.link
    pageUid="13"
    title="link with empty class"
    class="" />
<v:page.link
    pageUid="13"
    title="link with one space in class attribute"
    class=" " />
<v:page.link
    pageUid="13"
    title="link with two spaces in class attribute"
    class="  " />
<v:page.link
    pageUid="13"
    title="link with three spaces in class attribute"
    class="   " />

One class
<v:page.link
    pageUid="13"
    title="link with single class"
    class="test" />

Two classes
<v:page.link
    pageUid="13"
    title="link with two classes"
    class="test1 test2" />
<v:page.link
    pageUid="13"
    title="link with one spaces before two classes"
    class=" test1 test2" />
<v:page.link
    pageUid="13"
    title="link with two spaces before two classes"
    class="  test1 test2" />
<v:page.link
    pageUid="13"
    title="link with three spaces before two classes"
    class="   test1 test2" />
<v:page.link
    pageUid="13"
    title="link with one spaces behind two classes"
    class="test1 test2 " />
<v:page.link
    pageUid="13"
    title="link with two spaces behind two classes"
    class="test1 test2  " />
<v:page.link
    pageUid="13"
    title="link with three spaces behind two classes"
    class="test1 test2   " />
<v:page.link
    pageUid="13"
    title="link with one spaces behind and before two classes"
    class=" test1 test2 " />
<v:page.link
    pageUid="13"
    title="link with two spaces behind and before two classes"
    class="  test1 test2  " />
<v:page.link
    pageUid="13"
    title="link with three spaces behind and before two classes"
    class="   test1 test2   " />

```

Output before the patch:
====
```
No class attribute should be appear
<a title="link without class attribute" href="/index.php?id=13" class="">E-Commerce Consulting</a>
<a title="link with empty class" href="/index.php?id=13" class="">E-Commerce Consulting</a>
<a class="  " title="link with one space in class attribute" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="   " title="link with two spaces in class attribute" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="    " title="link with three spaces in class attribute" href="/index.php?id=13">E-Commerce Consulting</a>

One class
<a class="test " title="link with single class" href="/index.php?id=13">E-Commerce Consulting</a>

Two classes
<a class="test1 test2 " title="link with two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class=" test1 test2 " title="link with one spaces before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="  test1 test2 " title="link with two spaces before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="   test1 test2 " title="link with three spaces before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2  " title="link with one spaces behind two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2   " title="link with two spaces behind two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2    " title="link with three spaces behind two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class=" test1 test2  " title="link with one spaces behind and before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="  test1 test2   " title="link with two spaces behind and before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="   test1 test2    " title="link with three spaces behind and before two classes" href="/index.php?id=13">E-Commerce Consulting</a>

```

Output after the patch:
====
```
No class attribute should be appear
<a title="link without class attribute" href="/index.php?id=13">E-Commerce Consulting</a>
<a title="link with empty class" href="/index.php?id=13">E-Commerce Consulting</a>
<a title="link with one space in class attribute" href="/index.php?id=13">E-Commerce Consulting</a>
<a title="link with two spaces in class attribute" href="/index.php?id=13">E-Commerce Consulting</a>
<a title="link with three spaces in class attribute" href="/index.php?id=13">E-Commerce Consulting</a>

One class
<a class="test" title="link with single class" href="/index.php?id=13">E-Commerce Consulting</a>

Two classes
<a class="test1 test2" title="link with two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with one spaces before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with two spaces before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with three spaces before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with one spaces behind two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with two spaces behind two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with three spaces behind two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with one spaces behind and before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with two spaces behind and before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
<a class="test1 test2" title="link with three spaces behind and before two classes" href="/index.php?id=13">E-Commerce Consulting</a>
```

### CODE REVIEW

**Comment by cedricziel** [comment]
I'm fine with the changeset and corrected a variable name since we generally don't add suffixes that hint the type. Thx @beam2web .

**Comment by cedricziel** [comment]
Btw: A unit test says more than 1000 lines of markdown :)

The travis fail is related to deprecation warnings.

**Comment by beam2web** [comment]
> Btw: A unit test says more than 1000 lines of markdown :)
 I agree, but i'am not a backend developer and can't write it ;)

**Comment by NamelessCoder** [comment]
Please take care that you create patches starting from the `development` branch.

**Comment by NamelessCoder** [comment]
Thanks for the patch and welcome to the list of contributors! 🎉

**Pull request merged**
