### PR TITLE
[BUGFIX] enforce fixPermissions when writing asset files

### PR DESCRIPTION
**Pull request by peterkraume**
Sometimes TYPO3 caches can't be deleted with `typo3cms cache:flush --force` because of wrong file permissions of the EXT:vhs assets.
With this patch, `GeneralUtility:fixPermissions()` will be enforced to make use of `$TYPO3_CONF_VARS['BE']['fileCreateMask']`.

### CODE REVIEW

**Comment by cedricziel** [comment]
Thx for the change, @peterkraume !

**Comment by peterkraume** [comment]
👍 
Any idea when the next release of EXT:vhs is scheduled?

**Comment by cedricziel** [comment]
There's no schedule yet - @NamelessCoder can we have a new bugfix release, pleeeeeeaaaaaaaaaaase? :shamrock:

**Comment by cedricziel** [comment]
Not today, unfortunately - but maybe we can have a markdown file in the project that contains the release documentation? I think that's interesting for all of us who may tag and as far as I understood the release of the artifact is automated and there's not sensitive information - ayy?

**Comment by NamelessCoder** [comment]
Perhaps over the weekend then? I'd also like to discuss the current release process as well because it was created in 2012 or so and could use an update, maybe even some automation!

True, there's no sensitive information so it can be public docs. But if you don't mind, let's discuss first, maybe design a cleanup and *then* do and document it ;)

**Comment by cedricziel** [comment]
Alrighty - let's do this. I'll ping ya :)

**Comment by NamelessCoder** [comment]
Great! I should be available from tomorrow around lunchtime and I've got the entire weekend off :)

**Comment by peterkraume** [comment]
Guys, can we have a new release please?

**Pull request merged**
