### PR TITLE
[BUGFIX] Add fallback for deprecated argument

### LINKED ISSUE #1182: showHiddenInMenu attribute not used in v:condition.page.hasSubpages
`<v:condition.page.hasSubpages>` has a deprecated but still available attribute `showHiddenInMenu`. (It was deprecated in 3.0.0, #987)

Unfortunately, that attribute is not used at all, but is still advertised in the class docblock:

> To include pages that are hidden in menus set $showHiddenInMenu to TRUE.

The attribute should still work, even if it is deprecated.

### PR DESCRIPTION
**Pull request by bjo3rnf**
Closes #1182

### CODE REVIEW

**Comment by NamelessCoder** [comment]
A-updating we go, hey-ho. :)

**Comment by bjo3rnf** [comment]
It's that time of the year... ^^

**Comment by cedricziel** [comment]
Rebase or merge through web ui, I'm on mobile :)

**Comment by bjo3rnf** [comment]
Kazong!

**Comment by NamelessCoder** [comment]
compiling_4

**Comment by bjo3rnf** [comment]
@bjo3rnf is out of practice.

**Comment by bjo3rnf** [comment]
Like so?

**Comment by NamelessCoder** [comment]
Insert gif of Mythbusters snow plow of death with "git push -f" caption.

**Comment by bjo3rnf** [comment]
busted

**Pull request merged**
