### PR TITLE
[WIP] Image canvas feature

### PR DESCRIPTION
**Pull request by bjo3rnf**
This PR adds a new feature to ``v:media.image`` to create a canvas with given dimensions and background color to center an image on. This is useful in cases where images of different sizes and aspect ratios need to be displayed in a clean way without having to crop them.

Example: ``<v:media.image src="{image}" alt="" width="600" canvasWidth="800" canvasHeight="500" canvasColor="#cccccc" />``

Testing and feedback is welcome.

### CODE REVIEW

**Comment by danielkestler** [comment]
Great idea, will try it out.

**Comment by BenjaminBeck** [comment]
Hello bjo3rnf
I did test it and it works great.
Had to test some values until i found the best canvas size - but making this more easy would mean to support less usecases i guess..

THX 4 sharing
Benjamin

**Comment by NamelessCoder** [comment]
I think this looks reasonable enough - aside from the CGL issue in https://github.com/FluidTYPO3/vhs/pull/1047/files#diff-49eeb38c993b351e690866c88f8d0405R139 (indentation off by one). Would merge ;)

**Comment by bjo3rnf** [comment]
Oh noes. Conflicts.

**Comment by bjo3rnf** [comment]
Sorry for that diff but the file is one single CGL issue.

**Comment by NamelessCoder** [comment]
Will cherry-pick and fix this one first thing tomorrow - no worries ;)

**Comment by NamelessCoder** [comment]
IT'S IN THE BOOOOONE! https://github.com/FluidTYPO3/vhs/commit/1a356578733956c48be6c722fe0a7eba0605e622

**Comment by bjo3rnf** [comment]
Thanks! But the CGL...

**Pull request closed without merging**
