### PR TITLE
[BUGFIX] Add additional sanity checks for colPos and uid-lists

### PR DESCRIPTION
**Pull request by NamelessCoder**
Close: #1327

### CODE REVIEW

**Comment by bjo3rnf** [comment]
I can confirm this patch fixes the issue of all content elements with colPos 0 being unintentionally rendered.

**Comment by cedricziel** [comment]
@NamelessCoder care to check what's wrong here? Seems the ViewHelper is lacking the property `viewHelperNode` and thus the tests can't iterate on the childNodes

**Comment by NamelessCoder** [comment]
@cedricziel The composer deps are loose enough that we now get Fluid 2.4.0 so my guess would be that the VH is using some very old API that wasn't intended. Specifically it probably overrides a method it shouldn't or an additional method must be called from the unit test when building mock. If you have time, feel free to take a look - otherwise I'll take a look at the tests tonight.

**Comment by cedricziel** [comment]
Thx for the fix itself, and the upstream fixes as well, @NamelessCoder !

**Comment by NamelessCoder** [comment]
Was nothing, I wish I had caught this one earlier. Now the second problem with localisation config needs a solution so if you or someone else has time for that, please do take a look!

**Comment by TheNaderio** [comment]
I have flux, fluidpages and vhs all in latest development branch - and a fresh TYPO3 8.7.6
but my contentelement still renders twice.
It makes no difference if it is in colpos 0 or 1

**Pull request merged**
