### PR TITLE
[FEATURE] Filter by array in iterator.filter

### PR DESCRIPTION
**Pull request by Momodedf**
Sorry I could'nt include a test for this. Since it is juste a change on an existing feature I dont understand which kind of cases I should test.

### CODE REVIEW

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Comment by NamelessCoder** [comment]
Missing unit test is okay, but please do:

* Add a note in the `registerArgument` for the `filter` argument which explains what happens if you pass an array.

Then:

```
git commit --amend -a
```

And edit the subject to:

```
[FEATURE] Filter by array in iterator.filter
```

Finally,

```
git push --force
```

**Comment by NamelessCoder** [comment]
Hi @Momodedf - do you have time to amend this change? If not, just say the word and we will take care of implementing it.

**Comment by Momodedf** [comment]
Hi !
It's been a busy period and I didn't managed coming back to you.
I can do the changes and amend my commit very soon.

**Comment by NamelessCoder** [comment]
#### This is an automated comment based on an automated formal commit review.

Your pull request contains formal errors. Comments have been assigned to each commit in your pull request - please review and adjust. Feel free to ask for help if you need it!

**Pull request merged**
