### PR TITLE
Apply PSR-2 Code style

### PR DESCRIPTION
**Pull request by cedricziel**
Since core uses it, there's no reason why we shouldn't adopt it.

Closes: #978

### CODE REVIEW

**Comment by cedricziel** [comment]
ping @NamelessCoder :

Any objections if I'd re-apply PSR-2 with the core standard to all of our code base this weekend? I think it's best to just adopt the core style and its config so we don't have to take care about those issues anymore.

**Comment by NamelessCoder** [comment]
No objections from me - as long as you prepare them as PRs so we can merge them all at the same time. You may want to wait until at least tomorrow though, I might make a few releases later tonight.

**Comment by cedricziel** [comment]
I'm super fine with this. I'll do so tomorrow then.

**Comment by cedricziel** [comment]
Alright - I think this one's good to go, once FluidTYPO3/fluidtypo3-development#2 is in.

**Comment by bjo3rnf** [comment]
Let's do this.

**Comment by cedricziel** [comment]
Sure as hell. Please check https://github.com/FluidTYPO3/fluidtypo3-development/pull/2

**Comment by NamelessCoder** [comment]
Done, but with raw PSR-2 standard instead of TYPO3CMS one.

**Pull request closed without merging**
