### PR TITLE
[TASK] Re-implement excludeSubpageTypes argument

### PR DESCRIPTION
**Pull request by bjo3rnf**
Addresses #1329

### CODE REVIEW

**Comment by NamelessCoder** [comment]
I've had a bit of a think about this PR and https://github.com/FluidTYPO3/vhs/pull/1372 and I've come to the conclusion that the best way to handle this would be to pass the entire array of arguments to these functions, rather than extending the signature or creating an intermediate array to transfer arguments.

I've considered and opted against the following alternatives:

* Somehow making an `ArgumentCollection` that both defines and receives arguments for ViewHelpers, like a DTO that we can transfer. I chose not to since this very quickly over-complicated the VH structures.
* Inventing a "stupid" DTO rather than an array, with getters/setters to transfer things like requested menu configuration. I chose not to since this has very little difference to the $arguments array which we already have.

All in all I think a simple array is the most flexible method that isn't going to be too complex for contributors to understand. So my suggestion would be that in v5.0.0 we break these (internal) method signatures and switch to array as required type and then refactor as necessary to remove all other arguments than `array $arguments` from methods like `getMenu`.

And while doing so we should consider if this is the time to create services to return these things so we can begin cleaning up the class hierarchies and use simpler base classes!

**Comment by bjo3rnf** [comment]
Yes, agreed. I had a discussion about that with @cedricziel already and he proposed http://symfony.com/doc/current/components/options_resolver.html which would be a quite elegant solution.

**Comment by NamelessCoder** [comment]
That would work very well for our purposes, but I hesitate to introduce production composer dependencies until the time we pull the TER plug and go pure composer. Until then it's probably going to cause trouble for some users. Meanwhile we can at least implement safe fallbacks by using `array_replace($defaultsWeDefine, $arguments)` where this makes sense, for the methods we will refactor to receive arrays. Such defaults would make a nice static variable inside the method ;)

**Comment by bjo3rnf** [comment]
I see and agree. I'll close this one for now and try to come up with something new soon.

**Comment by NamelessCoder** [comment]
Thanks Björn, much appreciated :)

**Pull request closed without merging**
